// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// buildAstar
NumericMatrix buildAstar(NumericMatrix foinew, NumericMatrix ldfnew, int grainsize, bool debug);
RcppExport SEXP _Scalelink_buildAstar(SEXP foinewSEXP, SEXP ldfnewSEXP, SEXP grainsizeSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type foinew(foinewSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ldfnew(ldfnewSEXP);
    Rcpp::traits::input_parameter< int >::type grainsize(grainsizeSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(buildAstar(foinew, ldfnew, grainsize, debug));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Scalelink_buildAstar", (DL_FUNC) &_Scalelink_buildAstar, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Scalelink(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
